services:
  client:
    build: client
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    container_name: client
    restart: always
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - react-express

  server:
    container_name: server
    restart: always
    build: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    expose:
      - 8080
    networks:
      - express-mongo
      - react-express

  mongo:
    container_name: mongo
    restart: always
    image: mongo:7.0.0-rc8
    volumes:
      - ./data:/data/db
    expose:
      - 27017
    networks:
      - express-mongo

networks:
  react-express:
  express-mongo:
