version: "3.8"
services:
  client:
    build: client
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    container_name: client
    image: 807770787308.dkr.ecr.eu-west-1.amazonaws.com/todo_client:latest
    restart: always
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - react-express

  server:
    container_name: server
    restart: always
    build: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    expose:
      - 8080
    networks:
      - express-mongo
      - react-express
    image: 807770787308.dkr.ecr.eu-west-1.amazonaws.com/todo_server:latest

  mongo:
    container_name: mongo
    restart: always
    build: mongo
    volumes:
      - ./data:/data/db
    expose:
      - 27017
    networks:
      - express-mongo
    image: 807770787308.dkr.ecr.eu-west-1.amazonaws.com/todo_mongo:latest

networks:
  react-express:
  express-mongo:
