apiVersion: v1
kind: Service
metadata:
  name: service-np-mongo
  labels:
    name: testing-kube-deploy
    app: testing-kube-app
spec:
  type: NodePort
  selector:
    app: testing-kube-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
