apiVersion: v1
kind: Service
metadata:
  name: service-np-server
  labels:
    name: testing-kube-deploy
    app: testing-kube-app
spec:
  type: ClusterIP
  selector:
    app: testing-kube-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
